services:
  fastapi:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: dev_fastapi
    volumes:
      - ../:/workspace/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - PYTHONPATH=.
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/devdb

  postgres:
    image: postgres:15
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
