version: "3.8"

services:
  fastapi:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      PYTHONPATH: "/app"
      DATABASE_URL: postgresql://postgres:password@postgres:5432/devdb
    command:
      [
        "sh",
        "-c",
        "cd /app && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      ]

  postgres:
    image: postgres:15
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
